repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: debug-statements
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 54a455f7ce629598b7535ff828fd5fb796f4b83f  # frozen: v0.12.9
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: '412de98d50e846f31ea6f4b0ad036f2c24a7a024'  # frozen: v1.17.1
  hooks:
  - id: mypy
    files: supersmoother/
    additional_dependencies: [numpy>=2.2.0, scipy, scipy-stubs, pytest]
    args: [--config=pyproject.toml]
